#!/usr/bin/env tsx
/**
 * DTCG tokens.json  →  generated Tailwind theme + CSS custom properties.
 *
 * Writes two files:
 *   - tailwind.config.ts           (only the GENERATED block is managed)
 *   - src/styles/tokens.css        (fully generated — safe to overwrite)
 *
 * The generated block in tailwind.config.ts is delimited by markers so the
 * user can add plugins / content paths / etc. above or below without
 * losing them on regeneration.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { flatten, type DtcgGroup, type FlatToken } from "./tokens.ts";

const ROOT = resolve(import.meta.dirname, "..");
const TOKENS = resolve(ROOT, "tokens.json");
const TAILWIND = resolve(ROOT, "tailwind.config.ts");
const TOKENS_CSS = resolve(ROOT, "src/styles/tokens.css");

const BEGIN = "// BEGIN GENERATED — do not edit, managed by scripts/tokens-to-tailwind.ts";
const END = "// END GENERATED";

export interface EmitResult {
  tailwindBlock: string;
  css: string;
}

export function emit(tree: DtcgGroup): EmitResult {
  const tokens = flatten(tree);
  return {
    tailwindBlock: emitTailwind(tokens),
    css: emitCss(tokens),
  };
}

/**
 * A token path like `color.brand.primary.500` becomes the CSS var `--color-brand-primary-500`.
 * camelCase group names (e.g. `letterSpacing`, `borderWidth`, `zIndex`) are converted to
 * kebab-case so the resulting variable follows CSS conventions.
 */
export function cssVarName(path: string): string {
  const kebab = path.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
  return `--${kebab.replace(/\./g, "-")}`;
}

function emitCss(tokens: FlatToken[]): string {
  const lines: string[] = [
    "/* GENERATED by scripts/tokens-to-tailwind.ts — do not edit. */",
    ":root {",
  ];
  for (const t of tokens) {
    const rendered = renderCssValue(t);
    if (rendered === null) continue;
    lines.push(`  ${cssVarName(t.path)}: ${rendered};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function renderCssValue(t: FlatToken): string | null {
  switch (t.type) {
    case "color":
    case "dimension":
    case "duration":
      return String(t.value);
    case "number":
    case "fontWeight":
      return String(t.value);
    case "fontFamily":
      return Array.isArray(t.value)
        ? (t.value as string[]).map(quoteIfNeeded).join(", ")
        : String(t.value);
    case "cubicBezier":
      return Array.isArray(t.value) ? `cubic-bezier(${(t.value as number[]).join(", ")})` : null;
    case "shadow": {
      const s = t.value as {
        color: string; offsetX: string; offsetY: string; blur: string; spread: string; inset?: boolean;
      };
      const inset = s.inset ? "inset " : "";
      return `${inset}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`;
    }
    default:
      return null;
  }
}

function quoteIfNeeded(f: string): string {
  return /\s/.test(f) ? `"${f}"` : f;
}

/**
 * Build a Tailwind v3/v4-compatible theme.extend block. Values reference the
 * generated CSS variables so the runtime theme is CSS-driven.
 */
function emitTailwind(tokens: FlatToken[]): string {
  const colors: Record<string, unknown> = {};
  const spacing: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};
  const fontFamily: Record<string, string[]> = {};
  const fontSize: Record<string, string> = {};
  const fontWeight: Record<string, string> = {};
  const lineHeight: Record<string, string> = {};
  const letterSpacing: Record<string, string> = {};
  const borderWidth: Record<string, string> = {};
  const opacity: Record<string, string> = {};
  const boxShadow: Record<string, string> = {};
  const transitionDuration: Record<string, string> = {};
  const transitionTimingFunction: Record<string, string> = {};
  const screens: Record<string, string> = {};
  const zIndex: Record<string, string> = {};

  for (const t of tokens) {
    const v = `var(${cssVarName(t.path)})`;
    const tail = t.path.split(".").slice(1).join("-"); // drop top-level group

    switch (t.path.split(".")[0]) {
      case "color":
        setNested(colors, t.path.split(".").slice(1), v);
        break;
      case "space":
        spacing[tail] = v;
        break;
      case "radius":
        borderRadius[tail] = v;
        break;
      case "font":
        handleFont(t, tail, { fontFamily, fontSize, fontWeight, lineHeight });
        break;
      case "letterSpacing":
        letterSpacing[tail] = v;
        break;
      case "borderWidth":
        borderWidth[tail] = v;
        break;
      case "opacity":
        opacity[tail] = v;
        break;
      case "shadow":
        boxShadow[tail] = v;
        break;
      case "motion":
        if (t.path.startsWith("motion.duration.")) transitionDuration[tail.replace(/^duration-/, "")] = v;
        if (t.path.startsWith("motion.easing."))   transitionTimingFunction[tail.replace(/^easing-/, "")] = v;
        break;
      case "breakpoint":
        // Tailwind screens expects raw CSS values, not var() references.
        // Emit the resolved value directly so Tailwind can process breakpoints at build time.
        screens[tail] = String(t.value);
        break;
      case "zIndex":
        zIndex[tail] = v;
        break;
    }
  }

  const theme = {
    colors,
    spacing,
    borderRadius,
    fontFamily,
    fontSize,
    fontWeight,
    lineHeight,
    letterSpacing,
    borderWidth,
    opacity,
    boxShadow,
    transitionDuration,
    transitionTimingFunction,
    screens,
    zIndex,
  };

  // JSON.stringify produces valid TS here because every value is a string or nested object.
  return [
    BEGIN,
    `export const generatedTheme = ${JSON.stringify(theme, null, 2)};`,
    END,
  ].join("\n");
}

function setNested(obj: Record<string, unknown>, path: string[], value: unknown) {
  let cur: Record<string, unknown> = obj;
  for (let i = 0; i < path.length - 1; i++) {
    const k = path[i];
    if (!(k in cur) || typeof cur[k] !== "object" || cur[k] === null) cur[k] = {};
    cur = cur[k] as Record<string, unknown>;
  }
  // If the final key already holds an object (because a deeper leaf was set first),
  // store the scalar under a `DEFAULT` key — Tailwind treats this as the group's default value.
  const last = path[path.length - 1];
  const existing = cur[last];
  if (existing && typeof existing === "object") {
    (existing as Record<string, unknown>).DEFAULT = value;
  } else {
    cur[last] = value;
  }
}

function handleFont(
  t: FlatToken,
  tail: string,
  sinks: {
    fontFamily: Record<string, string[]>;
    fontSize: Record<string, string>;
    fontWeight: Record<string, string>;
    lineHeight: Record<string, string>;
  },
) {
  const v = `var(${cssVarName(t.path)})`;
  if (t.path.startsWith("font.family.")) {
    // Tailwind fontFamily wants a string[]; wrap the var in a single-element array.
    sinks.fontFamily[tail.replace(/^family-/, "")] = [v];
  } else if (t.path.startsWith("font.size.")) {
    sinks.fontSize[tail.replace(/^size-/, "")] = v;
  } else if (t.path.startsWith("font.weight.")) {
    sinks.fontWeight[tail.replace(/^weight-/, "")] = v;
  } else if (t.path.startsWith("font.lineHeight.")) {
    sinks.lineHeight[tail.replace(/^lineHeight-/, "")] = v;
  }
}

/** Replace (or append) the generated block inside an existing tailwind.config.ts. */
export function spliceGenerated(existing: string, newBlock: string): string {
  const beginIdx = existing.indexOf(BEGIN);
  const endIdx = existing.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) {
    // No marker yet — append to end.
    const sep = existing.endsWith("\n") ? "" : "\n";
    return `${existing}${sep}\n${newBlock}\n`;
  }
  const before = existing.slice(0, beginIdx);
  const after = existing.slice(endIdx + END.length);
  return `${before}${newBlock}${after}`;
}

export async function run(): Promise<void> {
  const tree = JSON.parse(readFileSync(TOKENS, "utf8")) as DtcgGroup;
  const { tailwindBlock, css } = emit(tree);

  mkdirSync(dirname(TOKENS_CSS), { recursive: true });
  writeFileSync(TOKENS_CSS, css);

  const existingTailwind = existsSync(TAILWIND)
    ? readFileSync(TAILWIND, "utf8")
    : defaultTailwindScaffold();
  const merged = spliceGenerated(existingTailwind, tailwindBlock);
  writeFileSync(TAILWIND, merged);

  console.log(`[tokens-to-tailwind] wrote ${TOKENS_CSS}`);
  console.log(`[tokens-to-tailwind] wrote ${TAILWIND}`);
}

function defaultTailwindScaffold(): string {
  return `import type { Config } from "tailwindcss";

${BEGIN}
export const generatedTheme = {};
${END}

const config: Config = {
  content: ["./src/**/*.{ts,tsx,html,mdx}", "./.storybook/**/*.{ts,tsx,mdx}"],
  theme: { extend: generatedTheme },
  plugins: [],
};

export default config;
`;
}

// Run when invoked directly (tsx scripts/tokens-to-tailwind.ts).
const invokedDirectly = import.meta.url === `file://${process.argv[1]}`;
if (invokedDirectly) {
  run().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
